# Generated by Django 4.2.6 on 2023-10-09 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "address",
                    models.TextField(
                        help_text="Complete residential address which made up of a house number, street name, town or city, zip code and etc. Eg, No 08, Allarai North Kodikamam, Jaffna, Sri Lanka, 40000.",
                        verbose_name="Complete residential address which made up of a house number, street name, town or city, zip code and etc.",
                    ),
                ),
            ],
            options={"db_table": "customer"},
        )
    ]
